version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ddcpts-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ddcpts}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ddcpts}
      POSTGRES_DB: ${POSTGRES_DB:-ddcpts}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
    container_name: ddcpts-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://ddcpts:ddcpts@db:5432/ddcpts}
      PYTHONUNBUFFERED: "1"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

volumes:
  db-data:

