name: ddcpts_mobile
description: Digital Dairy Collection & Payment Transparency System - Mobile App
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  # State Management
  provider: ^6.1.1
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage & Database
  sqflite: ^2.3.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # Offline Support & Sync
  connectivity_plus: ^5.0.2
  workmanager: ^0.5.2
  
  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  
  # Date & Time
  intl: ^0.19.0
  
  # Utilities
  uuid: ^4.3.3
  logger: ^2.0.2+1
  
  # Forms & Validation
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
