openapi: 3.0.3
info:
  title: DDCPTS API
  version: 0.1.0
servers:
  - url: http://localhost:8000
paths:
  /api/v1/auth/login:
    post:
      summary: Login with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required: [email, password]
      responses:
        '200':
          description: Tokens
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token: { type: string }
                  refresh_token: { type: string }
  /api/v1/auth/otp-send:
    post:
      summary: Send OTP via SMS
      responses:
        '200': { description: Queued }
  /api/v1/auth/verify-otp:
    post:
      summary: Verify OTP and issue tokens
      responses:
        '200': { description: Verified }
  /api/v1/farmers:
    post:
      summary: Create farmer
      responses:
        '201': { description: Created }
  /api/v1/farmers/{farmer_code}:
    get:
      summary: Get farmer profile and last deliveries
      parameters:
        - in: path
          name: farmer_code
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /api/v1/deliveries:
    get:
      summary: List deliveries
      parameters:
        - in: query
          name: station_id
          schema: { type: string }
        - in: query
          name: date
          schema: { type: string }
    post:
      summary: Create delivery and queue SMS
      responses:
        '201': { description: Created }
  /api/v1/reports/daily:
    get:
      summary: Daily totals and by farmer
      responses:
        '200': { description: OK }
  /api/v1/reports/monthly:
    get:
      summary: Monthly summary for farmer
      responses:
        '200': { description: OK }
  /api/v1/payments/disburse:
    post:
      summary: Initiate batch M-Pesa B2C payment
      parameters:
        - in: query
          name: month
          required: true
          schema: { type: string }
        - in: query
          name: sandbox
          schema: { type: boolean }
      responses:
        '202': { description: Queued }
  /api/v1/sync/batch:
    post:
      summary: Sync batch from mobile clients
      responses:
        '207': { description: Multi-status }

