name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ddcpts
          POSTGRES_PASSWORD: ddcpts
          POSTGRES_DB: ddcpts
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U ddcpts -d ddcpts" 
          --health-interval 5s --health-timeout 5s --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        working-directory: backend
        run: |
          ruff check app
      - name: Tests
        env:
          DATABASE_URL: postgresql+psycopg://ddcpts:ddcpts@localhost:5432/ddcpts
          ENV: test
        working-directory: backend
        run: |
          pytest -q
      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t ddcpts-backend:ci .

